//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorWebAssembly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorWebAssembly.Resources.LocalizationRes", typeof(LocalizationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string DxBlazorStringId_Accordion_FilterPanel_NullText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Accordion_FilterPanel_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DxBlazorStringId_Calendar_ClearButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Calendar_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DxBlazorStringId_Calendar_TodayButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Calendar_TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DxBlazorStringId_ColorPicker_CancelButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.ColorPicker_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color....
        /// </summary>
        public static string DxBlazorStringId_ColorPicker_CustomColor {
            get {
                return ResourceManager.GetString("DxBlazorStringId.ColorPicker_CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DxBlazorStringId_ColorPicker_OkButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.ColorPicker_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not match the required format..
        /// </summary>
        public static string DxBlazorStringId_DataEditor_InvalidMaskValidation {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataEditor_InvalidMaskValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_AllText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_CancelButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_CheckBoxColumn_FilterTextChecked {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_CheckBoxColumn_FilterTextChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_CheckBoxColumn_FilterTextIndeterminate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_CheckBoxColumn_FilterTextIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_CheckBoxColumn_FilterTextUnchecked {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_CheckBoxColumn_FilterTextUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_ClearButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_ColumnChooser {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_ColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Column.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_ColumnChooser_CommandColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_ColumnChooser_CommandColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Columns.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_ColumnChooser_Header {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_ColumnChooser_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Column.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_ColumnChooser_SelectionColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_ColumnChooser_SelectionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_DeleteButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_EditButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_EmptyDataRow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_GroupPanel {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string DxBlazorStringId_DataGrid_Loading {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_NewButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_PageSize {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_SummaryAvg {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_SummaryAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_SummaryCount {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_SummaryMax {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_SummaryMin {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_SummarySum {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DxBlazorStringId_DataGrid_UpdateButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DataGrid_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_ApplyButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_ChooseDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date and time.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_ChooseDateAndTime {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_ChooseDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_CloseButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_DateTab {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_DateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date is unavailable. Please choose a different date..
        /// </summary>
        public static string DxBlazorStringId_DateEdit_DisabledDateNotification {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_DisabledDateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_NowButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_NowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date should be between {0} and {1}..
        /// </summary>
        public static string DxBlazorStringId_DateEdit_OutOfRangeNotification {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_OutOfRangeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_TimeTab {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_TimeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DxBlazorStringId_Grid_ClearFilterButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_ClearFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        public static string DxBlazorStringId_Grid_ColumnChooser_HeaderText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_ColumnChooser_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_CancelButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_DeleteButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_DeleteConfirmationText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_EditButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_NewButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_PopupEditFormHeaderText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_PopupEditFormHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DxBlazorStringId_Grid_Editing_SaveButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Editing_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string DxBlazorStringId_Grid_EmptyDataRow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column here....
        /// </summary>
        public static string DxBlazorStringId_Grid_EmptyHeaders {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Next Month.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_BeyondNextMonth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_BeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier this Month.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_EarlierThisMonth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_EarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_LastMonth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_LastWeek {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later this Month.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_LaterThisMonth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_LaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_NextMonth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_NextWeek {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_Older {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Ago.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_ThreeWeeksAgo {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_ThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Away.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_ThreeWeeksAway {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_ThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_Today {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_Tomorrow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Ago.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_TwoWeeksAgo {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Away.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_TwoWeeksAway {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_TwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupInterval_DateRange_Yesterday {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupInterval_DateRange_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupPanel {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string DxBlazorStringId_Grid_Loading {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DxBlazorStringId_Grid_PageSizeSelector_AllRowsItem {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_PageSizeSelector_AllRowsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string DxBlazorStringId_Grid_PageSizeSelector_Caption {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_PageSizeSelector_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_Average {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg of {0}.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_AverageOfAnotherColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_AverageOfAnotherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_Count {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_Max {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max of {0}.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_MaxOfAnotherColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_MaxOfAnotherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_Min {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {0}.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_MinOfAnotherColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_MinOfAnotherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_Sum {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of {0}.
        /// </summary>
        public static string DxBlazorStringId_Grid_Summary_SumOfAnotherColumn {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_Summary_SumOfAnotherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string DxBlazorStringId_GroupControl_Collapse {
            get {
                return ResourceManager.GetString("DxBlazorStringId.GroupControl_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string DxBlazorStringId_GroupControl_Expand {
            get {
                return ResourceManager.GetString("DxBlazorStringId.GroupControl_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string DxBlazorStringId_ListBox_EmptyDataRow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.ListBox_EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DxBlazorStringId_No {
            get {
                return ResourceManager.GetString("DxBlazorStringId.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DxBlazorStringId_Pager_NextButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string DxBlazorStringId_Pager_PageOfLabel {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_PageOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string DxBlazorStringId_Pager_PrevButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_PrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string DxBlazorStringId_PivotGrid_GrandTotal {
            get {
                return ResourceManager.GetString("DxBlazorStringId.PivotGrid_GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Total.
        /// </summary>
        public static string DxBlazorStringId_PivotGrid_TotalFormat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.PivotGrid_TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DxBlazorStringId_Popup_CloseButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Popup_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_CancelButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Blue {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Cyan {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Green {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Indigo {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Light {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Orange {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Pink {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Purple {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Red {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Teal {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Yellow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_DayViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_DayViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_EmptyResource {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_EmptyResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_AllDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete only this appointment or the whole series?.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_ConfirmDelete {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit only this appointment or the whole series?.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_ConfirmEdit {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Days {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_DeleteButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete series.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_DeleteSeriesButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteSeriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Description {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Discard {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EditButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit series.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EditSeriesButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditSeriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EndDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Hours {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Label {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Location {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Months {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrence(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Occurrences {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Of {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_On {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_OnDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_OnThe {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Repeat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat {0}.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatAppointment {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat end.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatEnd {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatEvery {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Resource {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Save {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_StartDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Status {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Subject {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Title {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Weeks {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_MonthViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_MonthViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No subject).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_NoSubject {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_OkButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_EndAfter {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_EndBy {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No End Date.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_NoEndDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Daily {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Monthly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Never {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Weekly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Yearly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource name....
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Resources_FilterNullText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Resources_FilterNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Resources_SelectAll {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Resources_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ResourcesButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ResourcesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_SettingsToolbarTitle {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_SettingsToolbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Away {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Busy {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Free {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Tentative {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working elsewhere.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_WorkingElsewhere {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_WorkingElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_TimelineViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_TimelineViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_TodayButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Close {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Delete {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Edit {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Occurrence.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_RestoreOccurrence {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_RestoreOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_Day {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekend.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_Weekend {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_WorkDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_WorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_First {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Fourth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Last {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Second {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Third {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Week.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WorkWeekViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WorkWeekViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be less than or equal to {0}.
        /// </summary>
        public static string DxBlazorStringId_SpinEdit_InvalidMaxValueErrorFormat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.SpinEdit_InvalidMaxValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than or equal to {0}.
        /// </summary>
        public static string DxBlazorStringId_SpinEdit_InvalidMinValueErrorFormat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.SpinEdit_InvalidMinValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be in the range {0}...{1}.
        /// </summary>
        public static string DxBlazorStringId_SpinEdit_InvalidValueRangeErrorFormat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.SpinEdit_InvalidValueRangeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose time.
        /// </summary>
        public static string DxBlazorStringId_TimeEdit_ChooseTime {
            get {
                return ResourceManager.GetString("DxBlazorStringId.TimeEdit_ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected time value should be between {0} and {1}..
        /// </summary>
        public static string DxBlazorStringId_TimeEdit_OutOfRangeNotification {
            get {
                return ResourceManager.GetString("DxBlazorStringId.TimeEdit_OutOfRangeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string DxBlazorStringId_TreeView_FilterPanel_NullText {
            get {
                return ResourceManager.GetString("DxBlazorStringId.TreeView_FilterPanel_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string DxBlazorStringId_Upload_Canceled {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string DxBlazorStringId_Upload_Done {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string DxBlazorStringId_Upload_Failed {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large.
        /// </summary>
        public static string DxBlazorStringId_Upload_FileIsTooLarge {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too small.
        /// </summary>
        public static string DxBlazorStringId_Upload_FileIsTooSmall {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FileIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files ready to upload.
        /// </summary>
        public static string DxBlazorStringId_Upload_FilesToUpload {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were not uploaded.
        /// </summary>
        public static string DxBlazorStringId_Upload_FilesWereNotUploaded {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FilesWereNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file ready to upload.
        /// </summary>
        public static string DxBlazorStringId_Upload_FileToUpload {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not allowed.
        /// </summary>
        public static string DxBlazorStringId_Upload_FileTypeIsNotAllowed {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FileTypeIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file was not uploaded.
        /// </summary>
        public static string DxBlazorStringId_Upload_FileWasNotUploaded {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_FileWasNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to upload.
        /// </summary>
        public static string DxBlazorStringId_Upload_ReadyToUpload {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_ReadyToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string DxBlazorStringId_Upload_SelectFileButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_SelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file uploaded.
        /// </summary>
        public static string DxBlazorStringId_Upload_UploadedFile {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_UploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files uploaded.
        /// </summary>
        public static string DxBlazorStringId_Upload_UploadedFiles {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_UploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} file.
        /// </summary>
        public static string DxBlazorStringId_Upload_UploadingFile {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} files.
        /// </summary>
        public static string DxBlazorStringId_Upload_UploadingFiles {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Upload_UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DxBlazorStringId_Yes {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Yes", resourceCulture);
            }
        }
    }
}
