'------------------------------------------------------------------------------
' Generated by the DevExpress.Blazor package.
' To prevent this operation, add the DxExtendStartupHost property to the project and set this property to False.
'
' BlazorServerApp.csproj:
'
' <Project Sdk="Microsoft.NET.Sdk.Web">
'  <PropertyGroup>
'    <TargetFramework>netcoreapp3.1</TargetFramework>
'    <DxExtendStartupHost>False</DxExtendStartupHost>
'  </PropertyGroup>
'------------------------------------------------------------------------------
Imports Microsoft.Extensions.DependencyInjection
Imports Microsoft.AspNetCore.Hosting

<Assembly:HostingStartup(GetType(BlazorServerApp.DevExpressHostingStartup))>
Namespace BlazorServerApp

    Public Partial Class DevExpressHostingStartup
        Implements IHostingStartup

        Private Sub Configure(ByVal builder As IWebHostBuilder) Implements IHostingStartup.Configure
            builder.ConfigureServices(Sub(serviceCollection) serviceCollection.AddDevExpressBlazor())
        End Sub
    End Class
End Namespace
