Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace BlazorClientApp.Localization.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
	<System.Diagnostics.DebuggerNonUserCodeAttribute()>
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	Public Class LocalizationRes

		Private Shared resourceMan As System.Resources.ResourceManager

		Private Shared resourceCulture As System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
		Public Shared ReadOnly Property ResourceManager() As System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New System.Resources.ResourceManager("LocalizationRes", GetType(LocalizationRes).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
		Public Shared Property Culture() As System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Clear.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Calendar_ClearButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Calendar_ClearButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Today.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Calendar_TodayButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Calendar_TodayButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Apply.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_DateEdit_ApplyButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.DateEdit_ApplyButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Choose a date.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_DateEdit_ChooseDate() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.DateEdit_ChooseDate", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Close.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_DateEdit_CloseButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.DateEdit_CloseButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cancel.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_CancelButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_CancelButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Clear.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_ClearButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_ClearButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Delete.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_DeleteButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_DeleteButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Edit.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_EditButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_EditButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Drag a column header here to group by that column.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_GroupPanel() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_GroupPanel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to New.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_NewButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_NewButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Update.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Grid_UpdateButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Grid_UpdateButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Next.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Pager_NextButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Pager_NextButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to of.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Pager_PageOfLabel() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Pager_PageOfLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Prev.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Pager_PrevButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Pager_PrevButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Grand Total.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_PivotGrid_GrandTotal() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.PivotGrid_GrandTotal", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {0} Total.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_PivotGrid_TotalFormat() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.PivotGrid_TotalFormat", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Blue.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Blue() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Blue", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Cyan.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Cyan() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Cyan", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Green.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Green() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Green", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Indigo.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Indigo() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Indigo", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Light.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Light() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Light", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Orange.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Orange() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Orange", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Pink.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Pink() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Pink", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Purple.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Purple() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Purple", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Red.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Red() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Red", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Teal.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Teal() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Teal", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Yellow.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Color_Yellow() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Yellow", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Day.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_DayViewName() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_DayViewName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to All day.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_AllDay() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_AllDay", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Do you want to delete only this appointment or the whole series?.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_ConfirmDelete() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmDelete", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Do you want to edit only this appointment or the whole series?.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_ConfirmEdit() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmEdit", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to day(s).
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Days() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Days", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Delete appointment.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_DeleteButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Delete series.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_DeleteSeriesButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteSeriesButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Description.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Description() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Description", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Discard.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Discard() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Discard", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Edit appointment.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_EditButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Edit series.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_EditSeriesButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditSeriesButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to End.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_EndDate() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EndDate", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to hours.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Hours() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Hours", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Label.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Label() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Label", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Location.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Location() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Location", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to month(s).
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Months() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Months", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to occurrence(s).
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Occurrences() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Occurrences", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to of.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Of() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Of", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to On.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_On() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_On", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to On day.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_OnDay() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnDay", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to On the.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_OnThe() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnThe", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Repeat.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Repeat() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Repeat", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Repeat {0}.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_RepeatAppointment() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatAppointment", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Repeat end.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_RepeatEnd() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEnd", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Repeat every.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_RepeatEvery() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEvery", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Save.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Save() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Save", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Start.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_StartDate() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_StartDate", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Status.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Status() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Status", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Subject.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Subject() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Subject", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Appointment.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Title() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Title", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to week(s).
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Form_Weeks() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Weeks", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to (No subject).
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_NoSubject() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_NoSubject", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to End after.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceRange_EndAfter() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndAfter", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to End by.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceRange_EndBy() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndBy", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No End Date.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceRange_NoEndDate() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_NoEndDate", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Daily.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceType_Daily() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Daily", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Monthly.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceType_Monthly() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Monthly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Never.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceType_Never() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Never", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Weekly.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceType_Weekly() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Weekly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Yearly.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_RecurrenceType_Yearly() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Yearly", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Away.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Status_Away() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Away", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Busy.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Status_Busy() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Busy", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Free.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Status_Free() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Free", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Tentative.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Status_Tentative() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Tentative", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Working elsewhere.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_Status_WorkingElsewhere() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_WorkingElsewhere", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Today.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_TodayButton() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_TodayButton", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Close.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_ToolTip_Close() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Close", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Delete.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_ToolTip_Delete() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Delete", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Edit.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_ToolTip_Edit() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Edit", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Restore Occurrence.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_ToolTip_RestoreOccurrence() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_RestoreOccurrence", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to day.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekDays_Day() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Day", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to weekend.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekDays_Weekend() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Weekend", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to work day.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekDays_WorkDay() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_WorkDay", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to first.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekOfMonth_First() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_First", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to fourth.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekOfMonth_Fourth() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Fourth", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to last.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekOfMonth_Last() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Last", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to second.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekOfMonth_Second() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Second", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to third.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekOfMonth_Third() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Third", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Week.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WeekViewName() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekViewName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Work Week.
		''' </summary>
		Public Shared ReadOnly Property DxBlazorStringId_Scheduler_WorkWeekViewName() As String
			Get
				Return ResourceManager.GetString("DxBlazorStringId.Scheduler_WorkWeekViewName", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
