//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorClientApp.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorClientApp.Localization.Resources.LocalizationRes", typeof(LocalizationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DxBlazorStringId_Calendar_ClearButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Calendar_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DxBlazorStringId_Calendar_TodayButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Calendar_TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_ApplyButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_ChooseDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DxBlazorStringId_DateEdit_CloseButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.DateEdit_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DxBlazorStringId_Grid_CancelButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DxBlazorStringId_Grid_ClearButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DxBlazorStringId_Grid_DeleteButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DxBlazorStringId_Grid_EditButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        public static string DxBlazorStringId_Grid_GroupPanel {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DxBlazorStringId_Grid_NewButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DxBlazorStringId_Grid_UpdateButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Grid_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DxBlazorStringId_Pager_NextButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string DxBlazorStringId_Pager_PageOfLabel {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_PageOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string DxBlazorStringId_Pager_PrevButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Pager_PrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string DxBlazorStringId_PivotGrid_GrandTotal {
            get {
                return ResourceManager.GetString("DxBlazorStringId.PivotGrid_GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Total.
        /// </summary>
        public static string DxBlazorStringId_PivotGrid_TotalFormat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.PivotGrid_TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Blue {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Cyan {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Green {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Indigo {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Light {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Orange {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Pink {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Purple {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Red {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Teal {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Color_Yellow {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_DayViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_DayViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_AllDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete only this appointment or the whole series?.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_ConfirmDelete {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit only this appointment or the whole series?.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_ConfirmEdit {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Days {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_DeleteButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete series.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_DeleteSeriesButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_DeleteSeriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Description {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Discard {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EditButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit series.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EditSeriesButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EditSeriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_EndDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Hours {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Label {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Location {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Months {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrence(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Occurrences {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Of {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_On {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_OnDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_OnThe {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_OnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Repeat {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat {0}.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatAppointment {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat end.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatEnd {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_RepeatEvery {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Save {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_StartDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Status {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Subject {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Title {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Form_Weeks {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Form_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No subject).
        /// </summary>
        public static string DxBlazorStringId_Scheduler_NoSubject {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_EndAfter {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_EndBy {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No End Date.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceRange_NoEndDate {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceRange_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Daily {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Monthly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Never {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Weekly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_RecurrenceType_Yearly {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_RecurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Away {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Busy {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Free {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_Tentative {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working elsewhere.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_Status_WorkingElsewhere {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_Status_WorkingElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_TodayButton {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Close {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Delete {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_Edit {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Occurrence.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_ToolTip_RestoreOccurrence {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_ToolTip_RestoreOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_Day {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekend.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_Weekend {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work day.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekDays_WorkDay {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekDays_WorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_First {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Fourth {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Last {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Second {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekOfMonth_Third {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekOfMonth_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WeekViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WeekViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Week.
        /// </summary>
        public static string DxBlazorStringId_Scheduler_WorkWeekViewName {
            get {
                return ResourceManager.GetString("DxBlazorStringId.Scheduler_WorkWeekViewName", resourceCulture);
            }
        }
    }
}
